/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#0d1c2d",
        "secondary-fixed-dim": "#bec6e0",
        "outline-variant": "#464554",
        "on-primary-fixed": "#07006c",
        "on-secondary-container": "#adb4ce",
        "secondary": "#bec6e0",
        "surface-variant": "#273647",
        "on-tertiary-fixed": "#0d1c2f",
        "on-background": "#d4e4fa",
        "inverse-surface": "#d4e4fa",
        "on-surface-variant": "#c7c4d7",
        "primary-fixed": "#e1e0ff",
        "on-primary-container": "#0d0096",
        "secondary-fixed": "#dae2fd",
        "secondary-container": "#3f465c",
        "outline": "#908fa0",
        "primary-container": "#8083ff",
        "tertiary-fixed": "#d5e3fd",
        "primary-fixed-dim": "#c0c1ff",
        "surface-bright": "#2c3a4c",
        "on-secondary-fixed-variant": "#3f465c",
        "on-error": "#690005",
        "tertiary": "#b9c7e0",
        "error-container": "#93000a",
        "surface-tint": "#c0c1ff",
        "primary": "#c0c1ff",
        "on-secondary-fixed": "#131b2e",
        "on-surface": "#d4e4fa",
        "inverse-primary": "#494bd6",
        "surface-container-highest": "#273647",
        "surface-container-lowest": "#010f1f",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#2f2ebe",
        "background": "#051424",
        "tertiary-fixed-dim": "#b9c7e0",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface-dim": "#051424",
        "inverse-on-surface": "#233143",
        "tertiary-container": "#8392a9",
        "on-primary": "#1000a9",
        "on-tertiary": "#233144",
        "surface-container": "#122131",
        "surface": "#051424",
        "on-tertiary-container": "#1c2a3d",
        "surface-container-high": "#1c2b3c",
        "on-error-container": "#ffdad6",
        "on-secondary": "#283044"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "4px",
        "sm": "12px",
        "margin": "24px",
        "gutter": "20px",
        "md": "16px",
        "xs": "8px",
        "lg": "24px",
        "xl": "32px"
      },
      fontFamily: {
        "mono-label": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "label-caps": ["Inter"]
      },
      fontSize: {
        "mono-label": ["13px", { "lineHeight": "18px", "fontWeight": "450" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
