/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{html,js,svelte,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#b42900",
        "secondary-container": "#42b3ff",
        "error": "#ba1a1a",
        "surface-container": "#e6eeff",
        "on-tertiary-fixed-variant": "#454555",
        "on-primary-fixed-variant": "#891d00",
        "on-surface": "#121c2a",
        "secondary": "#006496",
        "surface-container-highest": "#d9e3f6",
        "tertiary": "#5a5b6b",
        "tertiary-fixed-dim": "#c6c5d8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "primary": "#af2800",
        "background": "#f8f9ff",
        "inverse-primary": "#ffb4a2",
        "outline": "#926f66",
        "tertiary-container": "#737384",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#001e31",
        "secondary-fixed-dim": "#91ccff",
        "on-background": "#121c2a",
        "surface-dim": "#d0dbed",
        "surface-container-high": "#dee9fc",
        "tertiary-fixed": "#e2e0f5",
        "on-primary-container": "#fffbff",
        "on-secondary-container": "#004367",
        "error-container": "#ffdad6",
        "primary-container": "#db3400",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#ffb4a2",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#5d3f38",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#3c0700",
        "surface": "#f8f9ff",
        "outline-variant": "#e7bdb3",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdad2",
        "on-secondary-fixed-variant": "#004b72",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed": "#1a1a28",
        "surface-variant": "#d9e3f6",
        "on-tertiary-container": "#fffbff",
        "secondary-fixed": "#cce5ff",
        "inverse-surface": "#27313f",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "base": "4px",
        "container-max": "1440px"
      },
      fontFamily: {
        "mono-sm": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "body-lg": ["Inter"],
        "headline-md": ["Geist"],
        "body-md": ["Inter"],
        "headline-lg": ["Geist"],
        "display-lg": ["Geist"],
        "headline-sm": ["Geist"],
        "label-md": ["Geist"]
      },
    },
  },
  plugins: [],
};
