-- Migration to support AI configuration (system prompt), stop triggers and intent rules
-- V20260727201345469__ai_configuration.sql

CREATE TABLE ai_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_prompt TEXT NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stop_trigger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_word VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE intent_rule (
    id VARCHAR(255) PRIMARY KEY,
    intent_name VARCHAR(255) NOT NULL,
    keywords TEXT NOT NULL,
    action VARCHAR(50) NOT NULL,
    priority INT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

-- Insert initial mockup data
INSERT INTO ai_config (id, system_prompt) VALUES (1, 'You are a highly analytical AI core developed for Synthetic Logic.
Your tone is clinical, precise, and devoid of unnecessary emotive flourishes.
Prioritize technical accuracy above all else.

Constraint 01: If a query is ambiguous, ask for technical specifications.
Constraint 02: Do not use bullet points for lists shorter than 3 items.
Constraint 03: Use ISO 8601 for all date references.');

INSERT INTO stop_trigger (trigger_word) VALUES ('ERR_TIMEOUT'), ('root_access'), ('[REDACTED]'), ('kernel_panic');

INSERT INTO intent_rule (id, intent_name, keywords, action, priority, enabled) VALUES
('rule-101', 'payment_failure', 'payment failed,error 402,unauthorized', 'HUMAN_TAKEOVER', 1, TRUE),
('rule-102', 'spam_detection', 'buy bitcoin,casino,win money', 'STOP_GENERATION', 2, TRUE);
