-- V20260727201222600__dialogue_history.sql
-- Migration to support dialogue turns and AI state for conversation history

CREATE TABLE dialogue_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_turns_count INTEGER NOT NULL DEFAULT 0,
    human_intervention_required BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dialogue_turn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dialogue_state_id BIGINT NOT NULL,
    sender VARCHAR(50) NOT NULL,
    message_text TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dialogue_turn_state FOREIGN KEY (dialogue_state_id) REFERENCES dialogue_state(id) ON DELETE CASCADE
);

CREATE INDEX idx_dialogue_turn_state_time ON dialogue_turn(dialogue_state_id, timestamp);
