-- V20260727201823201__ai_configuration.sql
-- Migration to support AI configuration (system prompt, stop-triggers, model version)

CREATE TABLE ai_configuration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_prompt TEXT NOT NULL,
    stop_triggers VARCHAR(1000) NOT NULL,
    model_version VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ai_configuration (system_prompt, stop_triggers, model_version) VALUES (
    'You are a highly analytical AI assistant specialized in technical documentation and software architecture. Your tone is professional, concise, and focused on providing empirical data and verifiable code snippets. Avoid flowery language or conversational fillers. When asked about complex systems, provide high-level abstractions followed by detailed component breakdowns.',
    '[{"keyword":"Exit","enabled":true},{"keyword":"Cancel","enabled":true},{"keyword":"Error","enabled":true}]',
    'GPT-4-Turbo'
);
