-- V20260727200727302__rate_limit_and_emulation.sql
-- Migration to support tracking sent messages for account-level daily rate limits.

CREATE TABLE tg_account_message_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_account_id BIGINT NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    message_text TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_message_log_tg_account FOREIGN KEY (tg_account_id) REFERENCES tg_accounts(id) ON DELETE CASCADE
);

CREATE INDEX idx_message_log_account_time ON tg_account_message_log(tg_account_id, sent_at);
