-- V20260727201345541__create_ignored_chats.sql
-- Create table for tracking ignored Telegram chats to be filtered out by the inbound listener.

CREATE TABLE ignored_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
