CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE proxy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host VARCHAR(255) NOT NULL,
    port INT NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    type VARCHAR(50) NOT NULL
);

CREATE TABLE tg_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    user_id BIGINT,
    proxy_id BIGINT,
    CONSTRAINT fk_tg_accounts_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE SET NULL,
    CONSTRAINT fk_tg_accounts_proxy FOREIGN KEY (proxy_id) REFERENCES proxy(id) ON DELETE SET NULL,
    CONSTRAINT uq_tg_accounts_proxy UNIQUE (proxy_id)
);
