-- V20260727201514623__init_warmup.sql
-- Create tables for tracking Telegram accounts and their warm-up task history.

CREATE TABLE telegram_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_name VARCHAR(255) UNIQUE NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL,
    warmup_stage VARCHAR(100) NOT NULL,
    trust_score DOUBLE PRECISION NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE warmup_task_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_account_id BIGINT NOT NULL,
    task_type VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    score_impact DOUBLE PRECISION NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_task_telegram_account FOREIGN KEY (telegram_account_id) REFERENCES telegram_accounts(id)
);
