-- V20260727201345674__create_dialogue_views_and_indexes.sql
-- Flyway migration to define optimized schema, view and indexes for cross-account dialogue statuses in the unified inbox.

CREATE TABLE IF NOT EXISTS telegram_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_name VARCHAR(255) UNIQUE NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL,
    warmup_stage VARCHAR(100) NOT NULL,
    trust_score DOUBLE PRECISION NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS conversations (
    id VARCHAR(255) PRIMARY KEY,
    telegram_account_id BIGINT NOT NULL,
    lead_username VARCHAR(100),
    lead_phone_number VARCHAR(100),
    status VARCHAR(100),
    updated_at TIMESTAMP,
    FOREIGN KEY (telegram_account_id) REFERENCES telegram_accounts(id)
);

-- Optimized index for conversation status and timestamp to ensure the unified inbox loads instantly
CREATE INDEX IF NOT EXISTS idx_conv_status_updated_at ON conversations(status, updated_at DESC);

-- View for unified cross-account queries
CREATE OR REPLACE VIEW unified_inbox_view AS
SELECT
    c.id AS conversation_id,
    c.telegram_account_id,
    c.lead_username,
    c.lead_phone_number,
    c.status AS conversation_status,
    c.updated_at AS conversation_updated_at,
    ta.session_name AS account_session_name,
    ta.warmup_stage AS account_warmup_stage,
    ta.trust_score AS account_trust_score
FROM conversations c
JOIN telegram_accounts ta ON c.telegram_account_id = ta.id;
